### ISSUE TITLE
Android 10 荣耀8x, 无法开启内部的交通银行 5.0.0 版本

### ISSUE THREAD

**Issue by mrjerometw** [2-young-2-simple/VirtualApp#11]
您好, 我用了许多不同32位元的模式，都可以成功复制且开启不同的APP。
但碰到交通银行5.0.0版本之后, 就开启失败了，这是错误的资讯，能否指点迷津呢?

```
2021-03-06 16:29:40.514 2391-2391/com.bankcomm.Bankcomm E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.bankcomm" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.jar", zip file "/data/app/com.bankcomm.Bankcomm-JQTg-KHWl9pyRqRSobrVBA==/base.apk"],nativeLibraryDirectories=[/data/app/com.bankcomm.Bankcomm-JQTg-KHWl9pyRqRSobrVBA==/lib/arm, /data/app/com.bankcomm.Bankcomm-JQTg-KHWl9pyRqRSobrVBA==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:270)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:920)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:1015)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
        at java.lang.reflect.Method.invoke(Native Method)
        at mirror.RefMethod.call(RefMethod.java:63)
        at com.lody.virtual.client.VClient.bindApplicationNoCheck(VClient.java:565)
        at com.lody.virtual.client.VClient.bindApplication(VClient.java:340)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:178)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleExecuteTransaction(HCallbackStub.java:115)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:86)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by lianglixin** [comment]
这种应用带有检测，开发者并不想应用在沙盒当中使用，加固使得应用必须在智慧型设备上直接使用。
