### ISSUE TITLE
Android11（一加8）运行32位微信报错

### ISSUE THREAD

**Issue by twoways** [2-young-2-simple/VirtualApp#18]
**我编译的是32位的工程，运行微信会报下面的错误：**
VAJni.cpp 文件里面我注释掉了hookAndroidVM，不然运行不起来。

I/MMKV: <native-bridge.cpp:95::JNI_OnLoad> current API level = 30
I/MMKV: <MMKV.cpp:192::initialize> page size:4096
I/MMKV: <MMKV.cpp:206::initializeMMKV> root dir: /data/user/0/io.busniess.va/virtual/data/user/0/com.tencent.mm/files/mmkv
W/CTAPermission: ApplicationContext is null, so bypass permission check!
I/chatty: uid=10330(io.busniess.va) com.tencent.mm identical 1 line
W/CTAPermission: ApplicationContext is null, so bypass permission check!
W/System.err: java.lang.RuntimeException: Unable to instantiate application com.tencent.mm.app.Application: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null
W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1244)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at mirror.RefMethod.call(RefMethod.java:63)
W/System.err:     at com.lody.virtual.client.VClient.bindApplicationNoCheck(VClient.java:568)
W/System.err:     at com.lody.virtual.client.VClient.bindApplication(VClient.java:343)
W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:178)
W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleExecuteTransaction(HCallbackStub.java:115)
W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:86)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:233)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8010)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
W/System.err: Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null
W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:170)
W/System.err:     at com.tencent.mm.app.Application.onBaseContextAttached(SourceFile:73)
W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:180)
W/System.err:     at android.app.Application.attach(Application.java:371)
W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1165)
W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
W/System.err: 	... 13 more
W/System.err: Caused by: java.lang.ExceptionInInitializerError
W/System.err:     at com.tencent.mm.vfs.h.irY(SourceFile:193)
W/System.err:     at com.tencent.mm.vfs.aa.g(SourceFile:485)
W/System.err:     at com.tencent.mm.app.MMApplicationWrapper.onBaseContextAttached(SourceFile:121)
W/System.err:     at com.tencent.mm.app.MMApplicationLike.onBaseContextAttached(SourceFile:169)
W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(SourceFile:67)
W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(SourceFile:60)
W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(SourceFile:53)
W/System.err:     at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnBaseContextAttached(SourceFile:45)
W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:162)
W/System.err: 	... 18 more

**Comment by twoways** [comment]
remove
